name: Auto Merge & Backup

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'backups/**'

permissions:
  contents: write   # allow pushing backups to the repo

jobs:
  merge-and-backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "codex-bot"
          git config user.email "codex-bot@example.com"

      - name: Mark as merge commit for backup
        id: merge_check
        run: echo "merge_commit=true" >> $GITHUB_OUTPUT

      - name: Backup changed files (flat list, skip renames)
        if: steps.merge_check.outputs.merge_commit == 'true'
        run: |
          set -e
          mkdir -p backups
          export TZ="Australia/Sydney"
          datetime=$(date +"%Y-%m-%dT%H%M%S.%3N")

          # Get commit message and make safe short description
          msg="${{ github.event.head_commit.message }}"
          desc="$(printf "%s" "$msg" | sed -n '2,$p' | sed -n '/./{p;q}')"
          if [ -z "$desc" ]; then
            desc="$(printf "%s" "$msg" | head -n 1)"
          fi
          safe_desc="$(printf "%s" "$desc" | tr ' ' '-' | tr -cd '[:alnum:]-')"
          safe_desc="${safe_desc:0:30}"

          echo "🔍 Comparing HEAD~1 to HEAD for changes..."
          CHANGED_FILES=$(git diff --name-only HEAD~1 HEAD --diff-filter=AM)

          if [ -z "$CHANGED_FILES" ]; then
            echo "No new or modified files in this push."
            exit 0
          fi

          for file in $CHANGED_FILES; do
            if [ -f "$file" ]; then
              base_name=$(basename "$file")
              ext="${base_name##*.}"
              name="${base_name%.*}"
              cp "$file" "backups/${name}-${datetime}-${safe_desc}.${ext}"
              echo "📦 Backed up: $file → backups/${name}-${datetime}-${safe_desc}.${ext}"
            fi
          done

          echo "✅ Backup completed. All files stored flat in backups/"

      - name: Commit backup
        if: steps.merge_check.outputs.merge_commit == 'true'
        run: |
          git add backups/
          if git diff --cached --quiet; then
            echo "No new backup created"
          else
            git commit -m "Backup changed files at $(date) for commit: ${{ github.sha }}"
            git push origin main
          fi
