// ============================================================================
// CONSOLE FILTER - Suppress known third-party warnings
// ============================================================================
// 
// This file is loaded conditionally via the Admin Settings checkbox
// "Enable Console Filter" - edit patterns below to customize filtering
//
// IMPORTANT: This filter ONLY suppresses JavaScript console.warn() messages.
// It does NOT suppress console.error() (errors are always critical and visible).
// It CANNOT suppress browser engine warnings like [Violation], [Intervention], 
// or [DOM] warnings - those are generated by Chrome's C++ engine before 
// JavaScript can intercept them.
//
// To hide browser warnings: Use Chrome DevTools filter (e.g. -[Violation])
//
// ============================================================================

(function(){
  'use strict';
  
  const originalWarn = console.warn;
  const originalError = console.error;
  
  // ========================================
  // SUPPRESSION PATTERNS - Edit as needed
  // ========================================
  
  const suppressedWarnings = [
    // Mapbox GL JS - Style loading (JS warning)
    /featureNamespace.*selector/i,
    
    // Mapbox GL JS - Terrain rendering (JS warning)
    /cutoff.*disabled.*terrain/i,
    
    // Mapbox GL JS - Missing marker composites (JS warning, expected during load)
    /Image "marker-label-composite.*could not be loaded/i,
  ];
  
  // Mapbox error patterns - suppress only specific known harmless Mapbox errors
  const suppressedErrors = [
    // Mapbox internal error: "Cannot read properties of null (reading 'dataset')"
    // This is a known harmless Mapbox internal error from their minified code
    // Match both parts to ensure we only catch this specific error
    /Cannot read properties of null.*dataset/i,
  ];
  
  // Check if error matches Mapbox dataset error specifically
  function isMapboxDatasetError(args) {
    var message = '';
    for(var i = 0; i < args.length; i++) {
      if(args[i] instanceof Error) {
        message += args[i].message + ' ' + (args[i].stack || '');
      } else {
        message += String(args[i]);
      }
      message += ' ';
    }
    return /Cannot read properties of null/i.test(message) && /dataset/i.test(message);
  }
  
  // ========================================
  // FILTER LOGIC - Do not edit below
  // ========================================
  
  function shouldSuppress(patterns, args) {
    // Convert all args to strings (handles Error objects)
    var message = '';
    for(var i = 0; i < args.length; i++) {
      if(args[i] instanceof Error) {
        message += args[i].message + ' ' + (args[i].stack || '');
      } else {
        message += String(args[i]);
      }
      message += ' ';
    }
    return patterns.some(function(pattern) { return pattern.test(message); });
  }
  
  console.warn = function(...args) {
    if(!shouldSuppress(suppressedWarnings, args)){
      originalWarn.apply(console, args);
    }
  };
  
  // Suppress only specific known harmless Mapbox errors
  console.error = function(...args) {
    // Check if it's the specific Mapbox dataset error
    if(isMapboxDatasetError(args)){
      return; // Suppress only this specific error
    }
    originalError.apply(console, args); // Show all other errors (including other Mapbox errors)
  };
  
  // Confirmation message
  console.log('%c[Console Filter Active]', 'color: #00ff00; font-weight: bold;', 
    'Suppressing', suppressedWarnings.length, 'warning patterns and', suppressedErrors.length, 'specific Mapbox error pattern.');
  
})();

