// ============================================================================
// CONSOLE FILTER - Suppress known third-party warnings
// ============================================================================
// 
// This file is loaded conditionally via the Admin Settings checkbox
// "Enable Console Filter" - edit patterns below to customize filtering
//
// IMPORTANT: This filter ONLY suppresses JavaScript console.warn() messages.
// It does NOT suppress console.error() (errors are always critical and visible),
// EXCEPT for a very narrow set of known-bad browser extension crashes (Keeper).
// It CANNOT suppress browser engine warnings like [Violation], [Intervention], 
// or [DOM] warnings - those are generated by Chrome's C++ engine before 
// JavaScript can intercept them.
//
// To hide browser warnings: Use Chrome DevTools filter (e.g. -[Violation])
//
// ============================================================================

(function(){
  'use strict';

  // This file is loaded on every page.
  // IMPORTANT: Do not depend on localStorage. Many dev workflows clear it frequently.
  // The admin setting (database source of truth) is applied by the app after settings load:
  //   - `index-new.js` calls `window.ConsoleFilter.enable()/disable()`

  const originalWarn = console.warn;
  const originalLog = console.log;

  let isEnabled = false;
  let errorHandler = null;
  let rejectionHandler = null;

  // ========================================
  // SUPPRESSION PATTERNS - Edit as needed
  // ========================================
  const suppressedWarnings = [
    // Mapbox GL JS - Style loading (JS warning)
    /featureNamespace.*selector/i,

    // Mapbox GL JS - Terrain rendering (JS warning)
    /cutoff.*disabled.*terrain/i,

    // Mapbox GL JS - Missing marker composites (JS warning, expected during load)
    /Image "marker-label-composite.*could not be loaded/i,
  ];

  // ========================================
  // EXTENSION IMMUNITY (Keeper) - Narrow and opt-in
  // ========================================
  //
  // Goal: Keep DevTools usable by preventing *known-bad extension-origin*
  // console spam (NOT site errors).
  //
  // Rules:
  // - Only when the Admin "Devtools Console Filter" switch is ON.
  // - Only when the error is clearly extension-origin (chrome-extension:// or edge-extension://).
  // - Only when it matches the known Keeper signature (dataset crash from 5.js/6.js).
  //
  // This does NOT "fix" Keeper. It simply prevents its known-bad errors from
  // flooding the console on this site.

  function isExtensionUrl(url) {
    return typeof url === 'string' && (url.indexOf('chrome-extension://') === 0 || url.indexOf('edge-extension://') === 0);
  }

  function stackMentionsExtension(stack) {
    if (typeof stack !== 'string') return false;
    return stack.indexOf('chrome-extension://') !== -1 || stack.indexOf('edge-extension://') !== -1;
  }

  function isKeeperDatasetSignature(message, stack) {
    var msg = String(message || '');
    var st = String(stack || '');
    // Core symptom
    if (!/reading ['"]dataset['"]/i.test(msg) && !/dataset/i.test(msg)) return false;
    // Common Keeper bundle paths
    if (/(chrome-extension|edge-extension):\/\/.*\/javascript\/[56]\.js/i.test(st)) return true;
    // If stack is missing, fall back to message-only match (still extension-origin gated elsewhere)
    return /Cannot read properties of (undefined|null).*dataset/i.test(msg);
  }

  var ignoredCounts = Object.create(null);
  var reportedOnce = Object.create(null);
  function noteIgnored(kind) {
    ignoredCounts[kind] = (ignoredCounts[kind] || 0) + 1;
    if (!reportedOnce[kind]) {
      reportedOnce[kind] = true;
      // Single line, once per session, so user knows immunity is doing something.
      originalLog.call(console, '[Console Filter] Ignoring known-bad extension error:', kind);
    }
  }

  function attachKeeperImmunity() {
    if (errorHandler || rejectionHandler) return;

    // Prevent default console output for matching extension-origin errors.
    // (This cannot stop every possible console message, but it stops the common
    // "Uncaught (in promise)" / global error spam in modern Chromium browsers.)
    errorHandler = function(e) {
      try {
        if (!e) return;
        var filename = String(e.filename || '');
        var message = String(e.message || '');
        var stack = (e.error && e.error.stack) ? String(e.error.stack) : '';

        if (!isExtensionUrl(filename) && !stackMentionsExtension(stack)) return;
        if (!isKeeperDatasetSignature(message, stack)) return;

        if (typeof e.preventDefault === 'function') e.preventDefault();
        noteIgnored('keeper-dataset');
      } catch (_) {}
    };

    rejectionHandler = function(e) {
      try {
        if (!e) return;
        var reason = e.reason;
        var message = reason && reason.message ? String(reason.message) : String(reason || '');
        var stack = reason && reason.stack ? String(reason.stack) : '';

        if (!stackMentionsExtension(stack) && !isExtensionUrl(message)) return;
        if (!isKeeperDatasetSignature(message, stack)) return;

        if (typeof e.preventDefault === 'function') e.preventDefault();
        noteIgnored('keeper-dataset');
      } catch (_) {}
    };

    window.addEventListener('error', errorHandler, true);
    window.addEventListener('unhandledrejection', rejectionHandler);
  }

  function detachKeeperImmunity() {
    if (errorHandler) window.removeEventListener('error', errorHandler, true);
    if (rejectionHandler) window.removeEventListener('unhandledrejection', rejectionHandler);
    errorHandler = null;
    rejectionHandler = null;
  }
  
    // ========================================
    // FILTER LOGIC - Do not edit below
    // ========================================
    
    function shouldSuppress(patterns, args) {
      // Convert all args to strings (handles Error objects)
      var message = '';
      for(var i = 0; i < args.length; i++) {
        if(args[i] instanceof Error) {
          message += args[i].message + ' ' + (args[i].stack || '');
        } else {
          message += String(args[i]);
        }
        message += ' ';
      }
      return patterns.some(function(pattern) { return pattern.test(message); });
    }
    
  function enable() {
    if (isEnabled) return;
    isEnabled = true;

    console.warn = function(...args) {
      if(!shouldSuppress(suppressedWarnings, args)){
        originalWarn.apply(console, args);
      }
    };

    attachKeeperImmunity();

    console.log('%c[Console Filter Active]', 'color: #00ff00; font-weight: bold;',
      'Suppressing', suppressedWarnings.length, 'JavaScript warning patterns. Extension immunity: Keeper dataset spam only.');
  }

  function disable() {
    if (!isEnabled) return;
    isEnabled = false;

    console.warn = originalWarn;
    detachKeeperImmunity();
    originalLog.call(console, '%c[Console Filter Disabled]', 'color: #ff9900; font-weight: bold;');
  }

  // Expose API so the admin setting (database) can control it without localStorage.
  window.ConsoleFilter = {
    enable,
    disable,
    isEnabled: function() { return isEnabled; }
  };

})();

