// ============================================================================
// CONSOLE FILTER - Suppress known third-party warnings
// ============================================================================
// 
// This file is loaded conditionally via the Admin Settings checkbox
// "Enable Console Filter" - edit patterns below to customize filtering
//
// IMPORTANT: This filter ONLY suppresses JavaScript console.warn() messages.
// It does NOT suppress console.error() (errors are always critical and visible).
// It CANNOT suppress browser engine warnings like [Violation], [Intervention], 
// or [DOM] warnings - those are generated by Chrome's C++ engine before 
// JavaScript can intercept them.
//
// To hide browser warnings: Use Chrome DevTools filter (e.g. -[Violation])
//
// ============================================================================

(function(){
  'use strict';
  
  const originalWarn = console.warn;
  
  // ========================================
  // SUPPRESSION PATTERNS - Edit as needed
  // ========================================
  
  const suppressedWarnings = [
    // Mapbox GL JS - Style loading (JS warning)
    /featureNamespace.*selector/i,
    
    // Mapbox GL JS - Terrain rendering (JS warning)
    /cutoff.*disabled.*terrain/i,
    
    // Mapbox GL JS - Missing marker composites (JS warning, expected during load)
    /Image "marker-label-composite.*could not be loaded/i,
    
    // NOTE: Browser engine warnings like [Violation], [Intervention], [DOM]
    // CANNOT be suppressed here. They are not JavaScript console.warn() calls.
    
    // Add your own JavaScript warning patterns below:
    // /pattern to match/i,
  ];
  
  // NOTE: We do NOT suppress console.error() - errors are always critical
  // const suppressedErrors = [];
  
  // ========================================
  // FILTER LOGIC - Do not edit below
  // ========================================
  
  function shouldSuppress(patterns, args) {
    const message = args.join(' ');
    return patterns.some(pattern => pattern.test(message));
  }
  
  console.warn = function(...args) {
    if(!shouldSuppress(suppressedWarnings, args)){
      originalWarn.apply(console, args);
    }
  };
  
  // DO NOT FILTER ERRORS - They are always critical
  // console.error remains unchanged
  
  // Confirmation message
  console.log('%c[Console Filter Active]', 'color: #00ff00; font-weight: bold;', 
    'Suppressing', suppressedWarnings.length, 'warning patterns. Errors are never suppressed.');
  
})();

