// ============================================================================
// CONSOLE FILTER - Suppress known third-party warnings
// ============================================================================
// 
// This file is loaded conditionally via the Admin Settings checkbox
// "Enable Console Filter" - edit patterns below to customize filtering
//
// IMPORTANT: This filter ONLY suppresses JavaScript console.warn() messages.
// It does NOT suppress console.error() (errors are always critical and visible).
// It CANNOT suppress browser engine warnings like [Violation], [Intervention], 
// or [DOM] warnings - those are generated by Chrome's C++ engine before 
// JavaScript can intercept them.
//
// To hide browser warnings: Use Chrome DevTools filter (e.g. -[Violation])
//
// ============================================================================

(function(){
  'use strict';
  
  const originalWarn = console.warn;
  
  // ========================================
  // SUPPRESSION PATTERNS - Edit as needed
  // ========================================
  
  const suppressedWarnings = [
    // Mapbox GL JS - Style loading (JS warning)
    /featureNamespace.*selector/i,
    
    // Mapbox GL JS - Terrain rendering (JS warning)
    /cutoff.*disabled.*terrain/i,
    
    // Mapbox GL JS - Missing marker composites (JS warning, expected during load)
    /Image "marker-label-composite.*could not be loaded/i,
  ];
  
  // ========================================
  // FILTER LOGIC - Do not edit below
  // ========================================
  
  function shouldSuppress(patterns, args) {
    // Convert all args to strings (handles Error objects)
    var message = '';
    for(var i = 0; i < args.length; i++) {
      if(args[i] instanceof Error) {
        message += args[i].message + ' ' + (args[i].stack || '');
      } else {
        message += String(args[i]);
      }
      message += ' ';
    }
    return patterns.some(function(pattern) { return pattern.test(message); });
  }
  
  console.warn = function(...args) {
    if(!shouldSuppress(suppressedWarnings, args)){
      originalWarn.apply(console, args);
    }
  };
  
  // DO NOT FILTER ERRORS - All errors are important and must be visible
  // console.error remains unchanged
  
  // Confirmation message
  console.log('%c[Console Filter Active]', 'color: #00ff00; font-weight: bold;', 
    'Suppressing', suppressedWarnings.length, 'JavaScript warning patterns. All errors remain visible.');
  
})();

