-- Venue Seeder v4 - Generated SQL
-- Generated: 2026-01-23T04:21:20.773522
-- Total venues: 5

-- =============================================
-- POSTS
-- =============================================

INSERT INTO `posts` (`id`, `post_key`, `member_id`, `member_name`, `subcategory_key`, `loc_qty`, `visibility`, `moderation_status`, `flag_reason`, `checkout_key`, `payment_status`, `expires_at`, `deleted_at`, `created_at`, `updated_at`) VALUES
(16, '16-sydney-opera-house', 2, NULL, 'theatres-concert-halls', 1, 'active', 'clean', NULL, 'premium-listing', 'paid', '2046-01-01 00:00:00', NULL, NOW(), NOW());
INSERT INTO `posts` (`id`, `post_key`, `member_id`, `member_name`, `subcategory_key`, `loc_qty`, `visibility`, `moderation_status`, `flag_reason`, `checkout_key`, `payment_status`, `expires_at`, `deleted_at`, `created_at`, `updated_at`) VALUES
(17, '17-sydney-harbour-bridge', 3, NULL, 'landmarks', 1, 'active', 'clean', NULL, 'premium-listing', 'paid', '2046-01-01 00:00:00', NULL, NOW(), NOW());
INSERT INTO `posts` (`id`, `post_key`, `member_id`, `member_name`, `subcategory_key`, `loc_qty`, `visibility`, `moderation_status`, `flag_reason`, `checkout_key`, `payment_status`, `expires_at`, `deleted_at`, `created_at`, `updated_at`) VALUES
(18, '18-bondi-beach', 4, NULL, 'parks-nature', 1, 'active', 'clean', NULL, 'premium-listing', 'paid', '2046-01-01 00:00:00', NULL, NOW(), NOW());
INSERT INTO `posts` (`id`, `post_key`, `member_id`, `member_name`, `subcategory_key`, `loc_qty`, `visibility`, `moderation_status`, `flag_reason`, `checkout_key`, `payment_status`, `expires_at`, `deleted_at`, `created_at`, `updated_at`) VALUES
(19, '19-taronga-zoo', 5, NULL, 'zoos-aquariums-wildlife', 1, 'active', 'clean', NULL, 'premium-listing', 'paid', '2046-01-01 00:00:00', NULL, NOW(), NOW());
INSERT INTO `posts` (`id`, `post_key`, `member_id`, `member_name`, `subcategory_key`, `loc_qty`, `visibility`, `moderation_status`, `flag_reason`, `checkout_key`, `payment_status`, `expires_at`, `deleted_at`, `created_at`, `updated_at`) VALUES
(20, '20-royal-botanic-garden-sydney', 6, NULL, 'parks-nature', 1, 'active', 'clean', NULL, 'premium-listing', 'paid', '2046-01-01 00:00:00', NULL, NOW(), NOW());

-- =============================================
-- POST_MEDIA
-- =============================================

INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(2, 16, '00000016-Sydney_Australia._(21339175489).jpg', 'https://cdn.funmap.com/post-images/2026-01/00000016-Sydney_Australia._(21339175489).jpg', 4588171, '{\"file_name\": \"Sydney_Australia._(21339175489).jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 4588171, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(2, 16, '00000016-Interior_of_Sydney_Opera_House_Concert_Hall_during_performance.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000016-Interior_of_Sydney_Opera_House_Concert_Hall_during_performance.jpg', 2926435, '{\"file_name\": \"Interior_of_Sydney_Opera_House_Concert_Hall_during_performance.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 2926435, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(2, 16, '00000016-Joan_Sutherland_Theatre_Interior.JPG', 'https://cdn.funmap.com/post-images/2026-01/00000016-Joan_Sutherland_Theatre_Interior.JPG', 1051991, '{\"file_name\": \"Joan_Sutherland_Theatre_Interior.JPG\", \"file_type\": \"image/jpeg\", \"file_size\": 1051991, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(3, 17, '00000017-Sydney_Harbour_Bridge-2022.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000017-Sydney_Harbour_Bridge-2022.jpg', 1521976, '{\"file_name\": \"Sydney_Harbour_Bridge-2022.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 1521976, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(3, 17, '00000017-Sydney_Harbour_Bridge_from_the_air.JPG', 'https://cdn.funmap.com/post-images/2026-01/00000017-Sydney_Harbour_Bridge_from_the_air.JPG', 734525, '{\"file_name\": \"Sydney_Harbour_Bridge_from_the_air.JPG\", \"file_type\": \"image/jpeg\", \"file_size\": 734525, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(3, 17, '00000017-Sydney_Harbour_Bridge_from_Circular_Quay.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000017-Sydney_Harbour_Bridge_from_Circular_Quay.jpg', 8177508, '{\"file_name\": \"Sydney_Harbour_Bridge_from_Circular_Quay.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 8177508, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(4, 18, '00000018-Bondi_from_above.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000018-Bondi_from_above.jpg', 7345306, '{\"file_name\": \"Bondi_from_above.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 7345306, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(4, 18, '00000018-A_rip_current_pouring_over_the_people_standing_on_rock_shore_at_the_northern_end_of_Bondi_beach.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000018-A_rip_current_pouring_over_the_people_standing_on_rock_shore_at_the_northern_end_of_Bondi_beach.jpg', 391684, '{\"file_name\": \"A_rip_current_pouring_over_the_people_standing_on_rock_shore_at_the_northern_end_of_Bondi_beach.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 391684, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(4, 18, '00000018-Bondi_Beach,_Sydney_(15175458494).jpg', 'https://cdn.funmap.com/post-images/2026-01/00000018-Bondi_Beach,_Sydney_(15175458494).jpg', 780475, '{\"file_name\": \"Bondi_Beach,_Sydney_(15175458494).jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 780475, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(5, 19, '00000019-Taronga_Park_Zoo_-7Sept2008.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000019-Taronga_Park_Zoo_-7Sept2008.jpg', 835461, '{\"file_name\": \"Taronga_Park_Zoo_-7Sept2008.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 835461, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(5, 19, '00000019-Rusticbridge.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000019-Rusticbridge.jpg', 1033829, '{\"file_name\": \"Rusticbridge.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 1033829, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(5, 19, '00000019-2022-06-25_Giraffes_in_Taronga_Zoo.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000019-2022-06-25_Giraffes_in_Taronga_Zoo.jpg', 4677850, '{\"file_name\": \"2022-06-25_Giraffes_in_Taronga_Zoo.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 4677850, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(6, 20, '00000020-Gates_at_Royal_Botanic_Gardens_viewed_from_Art_Gallery_Road.jpg', 'https://cdn.funmap.com/post-images/2026-01/00000020-Gates_at_Royal_Botanic_Gardens_viewed_from_Art_Gallery_Road.jpg', 5603754, '{\"file_name\": \"Gates_at_Royal_Botanic_Gardens_viewed_from_Art_Gallery_Road.jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 5603754, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(6, 20, '00000020-After_the_fire_-_The_Garden_Palace_(8005393749).jpg', 'https://cdn.funmap.com/post-images/2026-01/00000020-After_the_fire_-_The_Garden_Palace_(8005393749).jpg', 375021, '{\"file_name\": \"After_the_fire_-_The_Garden_Palace_(8005393749).jpg\", \"file_type\": \"image/jpeg\", \"file_size\": 375021, \"crop\": null}', NULL, NULL, NOW(), NOW());
INSERT INTO `post_media` (`member_id`, `post_id`, `file_name`, `file_url`, `file_size`, `settings_json`, `backup_json`, `deleted_at`, `created_at`, `updated_at`) VALUES
(6, 20, '00000020-A_view_of_Royal_Botanic_Garden_taken_from_Sydney_Tower.jpeg', 'https://cdn.funmap.com/post-images/2026-01/00000020-A_view_of_Royal_Botanic_Garden_taken_from_Sydney_Tower.jpeg', 6504334, '{\"file_name\": \"A_view_of_Royal_Botanic_Garden_taken_from_Sydney_Tower.jpeg\", \"file_type\": \"image/jpeg\", \"file_size\": 6504334, \"crop\": null}', NULL, NULL, NOW(), NOW());

-- =============================================
-- POST_MAP_CARDS
-- =============================================

INSERT INTO `post_map_cards` (`id`, `post_id`, `subcategory_key`, `title`, `description`, `media_ids`, `custom_text`, `custom_textarea`, `custom_dropdown`, `custom_checklist`, `custom_radio`, `public_email`, `phone_prefix`, `public_phone`, `venue_name`, `address_line`, `city`, `latitude`, `longitude`, `country_code`, `timezone`, `age_rating`, `website_url`, `tickets_url`, `coupon_code`, `session_summary`, `price_summary`, `amenity_summary`, `created_at`, `updated_at`) VALUES
(19, 16, 'theatres-concert-halls', 'Sydney Opera House', 'The Sydney Opera House is a multi-venue performing arts centre in Sydney, New South Wales, Australia. Located on the foreshore of Sydney Harbour, it is widely regarded as one of the world\'s most famous and distinctive buildings, and a masterpiece of 20th-century architecture.\n\nDesigned by Danish architect Jørn Utzon and completed by an Australian architectural team headed by Peter Hall, the building was formally opened by Queen Elizabeth II on 20 October 1973, 16 years after Utzon\'s 1957 selection as winner of an international design competition. The Government of New South Wales, led by the premier, Joseph Cahill, authorised work to begin in 1958 with Utzon directing construction. The government\'s decision to build Utzon\'s design is often overshadowed by circumstances that followed, including cost and scheduling overruns as well as the architect\'s ultimate resignation.\n\nPhoto: Bernard Spragg. NZ from Christchurch, New Zealand (CC0); BennyG3255 (CC BY-SA 4.0); MorePix (CC BY-SA 4.0)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sydney', -33.85681, 151.21514, 'AU', NULL, NULL, 'https://www.sydneyoperahouse.com', NULL, NULL, NULL, NULL, NULL, NOW(), NOW());
INSERT INTO `post_map_cards` (`id`, `post_id`, `subcategory_key`, `title`, `description`, `media_ids`, `custom_text`, `custom_textarea`, `custom_dropdown`, `custom_checklist`, `custom_radio`, `public_email`, `phone_prefix`, `public_phone`, `venue_name`, `address_line`, `city`, `latitude`, `longitude`, `country_code`, `timezone`, `age_rating`, `website_url`, `tickets_url`, `coupon_code`, `session_summary`, `price_summary`, `amenity_summary`, `created_at`, `updated_at`) VALUES
(20, 17, 'landmarks', 'Sydney Harbour Bridge', 'The Sydney Harbour Bridge is a steel through arch bridge in Sydney, New South Wales, Australia, spanning Sydney Harbour from the central business district (CBD) to the North Shore. The view of the bridge, the Harbour, and the nearby Sydney Opera House is widely regarded as an iconic image of Sydney, and of Australia itself. Nicknamed \"the Coathanger\" because of its arch-based design, the bridge carries rail, vehicular, bicycle and pedestrian traffic.\n\nUnder the direction of John Bradfield of the New South Wales Department of Public Works, the bridge was designed and built by British firm Dorman Long of Middlesbrough, and opened in 1932. The bridge\'s general design, which Bradfield tasked the NSW Department of Public Works with producing, was a rough copy of the Hell Gate Bridge in New York City. The design chosen from the tender responses was original work created by Dorman Long, who leveraged some of the design from its own Tyne Bridge.\n\nPhoto: Bookish Worm (CC BY-SA 4.0); Rodney Haywood (Attribution); JJ Harrison (https://www.jjharrison.com.au/) (CC BY-SA 3.0)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sydney', -33.85222222, 151.21055556, 'AU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NOW(), NOW());
INSERT INTO `post_map_cards` (`id`, `post_id`, `subcategory_key`, `title`, `description`, `media_ids`, `custom_text`, `custom_textarea`, `custom_dropdown`, `custom_checklist`, `custom_radio`, `public_email`, `phone_prefix`, `public_phone`, `venue_name`, `address_line`, `city`, `latitude`, `longitude`, `country_code`, `timezone`, `age_rating`, `website_url`, `tickets_url`, `coupon_code`, `session_summary`, `price_summary`, `amenity_summary`, `created_at`, `updated_at`) VALUES
(21, 18, 'parks-nature', 'Bondi Beach', 'Bondi Beach is a popular beach and the name of the surrounding suburb in Sydney, New South Wales, Australia. Bondi Beach is located 7 kilometres (4 miles) east of the Sydney central business district, in the local government area of Waverley Council, in the Eastern Suburbs. In the 2021 Australian census it had a population of 11,513 residents. Its postcode is 2026. Bondi, North Bondi and Bondi Junction are neighbouring suburbs. Bondi Beach is one of the most visited tourist sites in Australia, and the location of two series Bondi Rescue and Bondi Vet.\n\nPhoto: Nick Ang (CC BY-SA 4.0); Chen Hualin (CC BY-SA 4.0); Nicolas Lannuzel from Singapore, Singapore (CC BY-SA 2.0)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sydney', -33.891, 151.278, 'AU', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NOW(), NOW());
INSERT INTO `post_map_cards` (`id`, `post_id`, `subcategory_key`, `title`, `description`, `media_ids`, `custom_text`, `custom_textarea`, `custom_dropdown`, `custom_checklist`, `custom_radio`, `public_email`, `phone_prefix`, `public_phone`, `venue_name`, `address_line`, `city`, `latitude`, `longitude`, `country_code`, `timezone`, `age_rating`, `website_url`, `tickets_url`, `coupon_code`, `session_summary`, `price_summary`, `amenity_summary`, `created_at`, `updated_at`) VALUES
(22, 19, 'zoos-aquariums-wildlife', 'Taronga Zoo', 'Taronga Zoo Sydney is a government-run public zoo located in Sydney, New South Wales, Australia, in the Lower North Shore suburb of Mosman, on the shores of Sydney Harbour. It offers great views of Sydney Harbour and the city. The opening hours are between 9:30 a.m. to 4:30 p.m. (May to August) and 9:30 am to 5:00 pm (September to April). Taronga is an Aboriginal word meaning \"beautiful view\".\n\nIt was officially opened on 7 October 1916. Taronga Zoo Sydney is managed by the Zoological Parks Board of New South Wales, under the trading name Taronga Conservation Society, along with its sister zoo, the Taronga Western Plains Zoo in Dubbo.\n\nPhoto: Alex Dawson (CC BY-SA 2.0); .....Todd#661 (Public domain); Maksym Kozlenko (CC BY-SA 4.0)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sydney', -33.84333333, 151.24111111, 'AU', NULL, NULL, 'https://taronga.org.au/taronga-zoo', NULL, NULL, NULL, NULL, NULL, NOW(), NOW());
INSERT INTO `post_map_cards` (`id`, `post_id`, `subcategory_key`, `title`, `description`, `media_ids`, `custom_text`, `custom_textarea`, `custom_dropdown`, `custom_checklist`, `custom_radio`, `public_email`, `phone_prefix`, `public_phone`, `venue_name`, `address_line`, `city`, `latitude`, `longitude`, `country_code`, `timezone`, `age_rating`, `website_url`, `tickets_url`, `coupon_code`, `session_summary`, `price_summary`, `amenity_summary`, `created_at`, `updated_at`) VALUES
(23, 20, 'parks-nature', 'Royal Botanic Garden, Sydney', 'The Royal Botanic Garden, Sydney is a heritage-listed major 30-hectare (74-acre) botanical garden, event venue and public recreation area located at Farm Cove on the eastern fringe of the Sydney central business district, in the City of Sydney local government area of New South Wales, Australia.\n\nOpened in 1816, the garden is the oldest scientific institution in Australia and one of the most important historic botanical institutions in the world. The overall structure and key elements were designed by Charles Moore and Joseph Maiden, and various other elements designed and built under the supervision of Allan Cunningham, Richard Cunningham, and Carrick Chambers. The garden is owned by the Government of New South Wales and administered by the Royal Botanic Gardens and Domain Trust. The Botanic Garden, together with the adjacent Domain were added to the New South Wales State Heritage Register on 2 April 1999.\n\nPhoto: Bidgee (CC BY-SA 3.0 au); Photographic Collection from Australia (CC BY 2.0); Harveychl (CC BY-SA 4.0)', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Sydney', -33.86388889, 151.21694444, 'AU', NULL, NULL, 'https://www.botanicgardens.org.au/royal-botanic-garden-sydney', NULL, NULL, NULL, NULL, NULL, NOW(), NOW());